# Generated by Django 5.0.1 on 2024-01-15 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='test_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='用户名')),
                ('password', models.CharField(max_length=30, verbose_name='密码')),
                ('email', models.EmailField(blank=True, max_length=40, null=True, verbose_name='邮箱')),
                ('createTime', models.DateTimeField(auto_now_add=True, max_length=100, null=True, verbose_name='创建时间')),
                ('updateTime', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('yn', models.CharField(blank='是否有效', choices=[('YES', '是'), ('NO', '否')], max_length=100)),
            ],
        ),
    ]
